Repository 2024-Winter-Bootcamp-team-K/AILIBI-Backend, pull requests merged in 2025-01, with the labels that each got.

#19 fix: 파일 디렉토리 수정 및 도커 파이썬 버전 수정
  Backend/settings.py
  Dockerfile
  scenario/__init__.py
  scenario/admin.py
  scenario/apps.py
  scenario/migrations/__init__.py
  scenario/models.py
  scenario/tests.py
  scenario/views.py
  stt/__init__.py
  stt/admin.py
  stt/apps.py
  stt/migrations/__init__.py
  stt/models.py
  stt/tests.py
  stt/views.py
  tts/__init__.py
  tts/admin.py
  tts/apps.py
  tts/migrations/__init__.py
  tts/models.py
  tts/tests.py
  tts/views.py
Labels: ❤️‍🔥BugFix

#21 Design ReadMe파일 수정
  README.md
Labels: 🎨Design

#23 feat: requiremens.txt 파일 업데이트
  requirements.txt
Labels: ✨Feat

#25 feat: cicd, Docker 연동
  .github/workflows/ci.yml
Labels: ✨Feat

#27 fix: DB 세팅 오류 수정
  Backend/settings.py
Labels: ❤️‍🔥BugFix

#29 refactor: requirements.txt 불 필요한 pip 제거
  requirements.txt
Labels: 🔨Refactor

#31 feat: django-channels 연동
  Backend/asgi.py
  Backend/settings.py
  llama3/consumers.py
  llama3/routing.py
  requirements.txt
Labels: ✨Feat

#43 feat: PostgreSQL, Docker 연동
  .github/workflows/ci.yml
  docker-compose.yml
  requirements.txt
Labels: ✨Feat

#56 feat: llm 모델 및 redis 연동
  .github/workflows/ci.yml
  Backend/asgi.py
  Backend/settings.py
  docker-compose.yml
  llama3/consumers.py
  llm/__init__.py
  llm/admin.py
  llm/apps.py
  llm/consumers.py
  llm/migrations/__init__.py
  llm/models.py
  llm/routing.py
  llm/serializers.py
  llm/tasks.py
  llm/tests.py
  llm/urls.py
  llm/views.py
  requirements.txt
  user/migrations/0002_alter_user_password.py
Labels: ✨Feat

#60 chore: 데이터 컬럼 및 속성 변경
  chat/models.py
  evidence/models.py
  scenario/models.py
  suspect/models.py
  user/models.py
Labels: ⚙️ Chore

#62 feat: DALL-E-3 연동 완료
  llm/consumers.py
Labels: ✨Feat

#64 refactor: chat과 llm 분리
  Backend/asgi.py
  chat/consumers.py
  chat/routing.py
  llm/views.py
Labels: 🔨Refactor

#79 feat: TTS APP 구현 및 CELERY, RABBITMQ 연동 완료
  Backend/__init__.py
  Backend/celery.py
  Backend/settings.py
  Backend/urls.py
  docker-compose.yml
  requirements.txt
  tts/models.py
  tts/tasks.py
  tts/urls.py
  tts/views.py
Labels: ✨Feat

#82 bug fix
  scenario/views.py
Labels: ❤️‍🔥BugFix

#84 Feat/#83
  llm/views.py
  suspect/models.py
Labels: 🔨Refactor, ✨Feat

#86 Chat app 초안
  chat/consumers.py
  chat/routing.py
  requirements.txt
Labels: ✨Feat

#87 [feat]change db and advence_llm
  chat/models.py
  llm/views.py
  suspect/models.py
Labels: 🔨Refactor, ✨Feat

#88 Chat App 코드 완성본
  chat/consumers.py
Labels: 🔨Refactor

#92 fix: migrations 오류 수정
  chat/migrations/0003_remove_chat_init_chat.py
  evidence/urls.py
  suspect/migrations/0003_remove_suspect_personality_suspect_description_and_more.py
  suspect/models.py
  suspect/urls.py
Labels: ❤️‍🔥BugFix

#90 test 오류버전
  Backend/settings.py
  Backend/urls.py
  chat/consumers.py
  chat/routing.py
  chat/templates/test.html
  chat/urls.py
  chat/views.py
Labels: ✨Feat

#96 fix: 웹소켓 연동 문제 해결
  Backend/settings.py
  chat/consumers.py
  chat/routing.py
  docker-compose.yml
Labels: ❤️‍🔥BugFix

#101 change to API fix
  Backend/urls.py
  user/users_urls.py
  user/views.py
Labels: ❤️‍🔥BugFix

#104 feat: tts, suspect, evidence Swagger 명세서 작성
  Backend/settings.py
  Backend/urls.py
  evidence/views.py
  suspect/serializers.py
  suspect/views.py
  tts/views.py
Labels: ✨Feat

#107 Feat/#106 swagger 명세서 작성 및 오류 수정
  scenario/serializers.py
  scenario/views.py
  user/views.py
Labels: ✨Feat, ❤️‍🔥BugFix

#109 Chat App 구현 환료 (프롬프팅 필요)
  chat/consumers.py
Labels: ✨Feat

#112 feat: S3 연동 완료
  Backend/settings.py
  llm/views.py
  requirements.txt
Labels: ✨Feat

#111 make test code and fix about DB column change
  scenario/serializers.py
  scenario/tests.py
  scenario/views.py
  user/tests.py
Labels: 🔨Refactor

#115 chore: 파일 디렉토리 수정
  chat/admin.py
  chat/apps.py
  chat/serializers.py
  chat/tests.py
  evidence/admin.py
  evidence/apps.py
  evidence/tests.py
  llm/admin.py
  llm/apps.py
  llm/models.py
  llm/serializers.py
  llm/tasks.py
  llm/tests.py
  scenario/admin.py
  scenario/apps.py
  scenario/tests.py
  stt/admin.py
  stt/apps.py
  stt/models.py
  stt/tests.py
  stt/urls.py
  stt/views.py
  suspect/admin.py
  suspect/apps.py
  suspect/tests.py
  tts/admin.py
  tts/apps.py
  tts/models.py
  tts/tests.py
Labels: ⚙️ Chore

#117 Make LLM swagger and complement create evidence
  llm/urls.py
  llm/views.py
Labels: ✨Feat

#118 Chat App Logging, Swagger 및 Test Code 작성
  chat/Serializers.py
  chat/consumers.py
  chat/urls.py
  chat/views.py
Labels: ✨Feat

#121 feat: Docker Blue-Green Deployment 적용
  .github/workflows/ci.yml
  Dockerfile
  docker-compose-blue.yml
  docker-compose-common.yml
  docker-compose-green.yml
Labels: ✨Feat

#124 change to use swagger
  Backend/settings.py
  Backend/urls.py
  Dockerfile
Labels: ✨Feat

#126 bug fix
  llm/views.py
Labels: ❤️‍🔥BugFix

#128 Feat:Make Monitoring
  docker-compose-common.yml
  prometheus.yml
Labels: ✨Feat

#129 1차 프롬프팅 완료
  chat/consumers.py
  chat/templates/test.html
Labels: 🔨Refactor

#131 feat:deploy success and ready to API connection
  docker-compose-common.yml
  nginx.conf
Labels: ✨Feat

#133 design: Swagger Title 및 Description 수정
  Backend/urls.py
Labels: 🎨Design

#135 refactor: Urls 형식 수정 완료
  Backend/urls.py
  chat/routing.py
  chat/urls.py
  evidence/urls.py
  suspect/urls.py
  tts/urls.py
  user/urls.py
Labels: 🔨Refactor

#138 feat:HTTPS connection
  docker-compose-common.yml
Labels: ✨Feat

#140 feat:edit nginx.conf
  nginx.conf
Labels: ✨Feat

#142 feat:HTTPS complete
  Backend/settings.py
  docker-compose-common.yml
  nginx.conf
  requirements.txt
Labels: ✨Feat

#146 feat: cors 권한 부여
  Backend/settings.py
Labels: ✨Feat

#148 chore: ci.yml 파일 수정
  .github/workflows/ci.yml
  Backend/settings.py
Labels: ⚙️ Chore

#152 fix: CORS 설정 추가 및 API Method 추가
  Backend/settings.py
  chat/views.py
  evidence/views.py
  llm/views.py
  scenario/views.py
  suspect/views.py
  tts/views.py
  user/views.py
Labels: ❤️‍🔥BugFix

#156 fix : Asynchronous
  evidence/views.py
  llm/views.py
  scenario/views.py
  suspect/views.py
  user/serializers.py
  user/views.py
Labels: ❤️‍🔥BugFix

#160 fix: 각종 오류 해결
  chat/views.py
  evidence/views.py
  llm/views.py
  nginx.conf
  scenario/views.py
  suspect/views.py
  tts/views.py
  user/views.py
Labels: ❤️‍🔥BugFix

#163 fix: Ryan 멘토님 피드백 기반 Swagger CORS 오류 해결 및 파이프라인 수정
  .github/workflows/ci.yml
  Backend/settings.py
  Backend/urls.py
  chat/views.py
  llm/views.py
  nginx.conf
  scenario/views.py
  tts/views.py
  user/views.py
Labels: ❤️‍🔥BugFix

#166 refactor: requirements.txt 간소화
  requirements.txt
Labels: 🔨Refactor

#168 chore: 파이프라인 빌드 수정
  .github/workflows/ci.yml
Labels: ⚙️ Chore

#170 chore: test, deploy 종속성 해제
  .github/workflows/ci.yml
Labels: ⚙️ Chore

#171 fix: bugs. init_chat 관련 DB 변경 반영
  scenario/views.py
  suspect/serializers.py
  suspect/views.py
  user/views.py
Labels: ❤️‍🔥BugFix

#173 chore: 파이프라인 git pull 추가
  .github/workflows/ci.yml
Labels: ⚙️ Chore

#175 feat:nginx logging
  nginx.conf
Labels: ✨Feat

#179 chore: 파이프라인 git pull 변경 및 django 보안 강화
  .github/workflows/ci.yml
  Backend/settings.py
Labels: ⚙️ Chore

#181 fix: swagger rollback
  Backend/settings.py
Labels: ❤️‍🔥BugFix

#183 feat:ADD wws and security
  Backend/asgi.py
  Backend/routing.py
  Backend/settings.py
  nginx.conf
Labels: ✨Feat

#185 feat: user app 비동기 전환
  user/views.py
Labels: ✨Feat

#187 fix: my fault
  Backend/asgi.py
  Backend/routing.py
Labels: ❤️‍🔥BugFix

#189 fix: 라우팅 오류 수정
  Backend/asgi.py
Labels: ❤️‍🔥BugFix

#191 fix: user app 동기 변경 및 파이프라인 test 수정
  .github/workflows/ci.yml
  user/serializers.py
  user/views.py
Labels: ❤️‍🔥BugFix

#193 fix: 파이프라인 도커 설치로 변경 및 API 오류 수정
  .github/workflows/ci.yml
  Backend/settings.py
  llm/views.py
  stt/views.py
Labels: ❤️‍🔥BugFix

#199 fix: 파이프라인 머지 시에 test 안돌아가게 변경
  .github/workflows/ci.yml
  scenario/serializers.py
  scenario/views.py
  stt/views.py
Labels: ❤️‍🔥BugFix

#203 fix: 시나리오 생성 API 수정
  llm/views.py
  stt/urls.py
Labels: ❤️‍🔥BugFix

#205 fix: STT API 수정 및 시나리오 생성 API 롤 백
  llm/views.py
  stt/views.py
Labels: ❤️‍🔥BugFix

#208 fix: 시나리오 생성 swagger 수정 및 stt 로깅 추가
  llm/views.py
  stt/views.py
Labels: ❤️‍🔥BugFix

#210 fix: stt 파일임시 저장 삭제 및 메모리 처리로 변경
  stt/views.py
Labels: ❤️‍🔥BugFix

#206 모니터링 매트릭 설정
  Backend/settings.py
  Backend/urls.py
  Dockerfile
  alertmanager/alertmanager.yml
  docker-compose-blue.yml
  docker-compose-common.yml
  grafana/data/alerting/1/__default__.tmpl
  grafana/data/grafana.db
  prometheus.yml
  prometheus/alert-rules.yml
  prometheus/prometheus.yml
  requirements.txt
  start_celery_flower.sh
Labels: 🔨Refactor

#214 chore: 파이프라인 세팅 변경
  .github/workflows/ci.yml
Labels: ⚙️ Chore

#217 fix and feat:wss and fix bug
  .gitignore
  docker-compose-common.yml
  promtail/config.yaml
Labels: ✨Feat, ❤️‍🔥BugFix

#219 feat: url encoded
  llm/views.py
Labels: ✨Feat

#221 fix: image url fix
  llm/views.py
Labels: ❤️‍🔥BugFix

#223 fix: chat api 수정
  chat/consumers.py
  chat/views.py
Labels: ❤️‍🔥BugFix

#225 fix: chat api url fix
  chat/urls.py
Labels: ❤️‍🔥BugFix

#227 fix: chat api url fix
  chat/urls.py
Labels: ❤️‍🔥BugFix

#229 fix: chat api fix
  chat/views.py
Labels: ❤️‍🔥BugFix

#231 fix:bug fix on suspect
  suspect/serializers.py
Labels: ❤️‍🔥BugFix

#232 모니터링 오류 수정
  Backend/settings.py
  docker-compose-blue.yml
  docker-compose-common.yml
Labels: ❤️‍🔥BugFix

#238 feat: aws cloudfront 세팅
  Backend/settings.py
  Backend/urls.py
Labels: ✨Feat

#240 fix: 살아나라 서버야ㅐ
  Backend/settings.py
  Backend/urls.py
Labels: ❤️‍🔥BugFix

#242 fix: 울고 싶어요
  Backend/settings.py
Labels: ❤️‍🔥BugFix

#244 fix: cloudfront 나가
  .gitignore
  Backend/settings.py
  grafana/data/grafana.db
  nginx.conf
Labels: ❤️‍🔥BugFix

#245 Delete grafana/data directory
  Backend/settings.py
  grafana/data/alerting/1/__default__.tmpl
  grafana/data/grafana.db
Labels: ❤️‍🔥BugFix

#247 fix: nginx.conf ws wrong proxy && scenario API view && task_id logic fix
  llm/views.py
  nginx.conf
  scenario/views.py
Labels: ❤️‍🔥BugFix

#249 fix: ws bug
  nginx.conf
Labels: ❤️‍🔥BugFix

#253 feat: 시나리오 생성 scenario_id 먼저 반환
  llm/views.py
Labels: ✨Feat

#255 refactor: 시나리오 불러오기 suspect, evidence 주석 해제
  scenario/views.py
Labels: 🔨Refactor

#257 fix: 시나리오 생성 오류 수정
  llm/views.py
Labels: ❤️‍🔥BugFix

#259 fix: 시나리오 생성 오류 수정 v2
  llm/views.py
Labels: ❤️‍🔥BugFix

#261 feat:promporting
  chat/consumers.py
  llm/views.py
Labels: 🔨Refactor, ✨Feat

#263 대시 보드 재생성 및 그라파나 연결, postgreSQL 모니터링 삭제
  .gitignore
  Backend/settings.py
  docker-compose-blue.yml
  docker-compose-common.yml
  grafana/data/alerting/1/__default__.tmpl
  grafana/data/grafana.db
  nginx.conf
  prometheus/prometheus.yml
Labels: ❤️‍🔥BugFix

#265 docker-compose-blue grafana 수정
  docker-compose-blue.yml
Labels: ❤️‍🔥BugFix

#268 chat DB데이터 저장 로직 수정
  chat/consumers.py
  grafana/data/grafana.db
Labels: ❤️‍🔥BugFix

#271 fix: fix the prompt
  chat/consumers.py
Labels: ❤️‍🔥BugFix

#273 fix: fix suspect & evidence create
  llm/urls.py
Labels: ❤️‍🔥BugFix

#278 fix: 시나리오 생성 로직 변경
  llm/urls.py
  llm/views.py
Labels: ❤️‍🔥BugFix

#281 fix: 시나리오 생성 로직 수정
  llm/views.py
Labels: ❤️‍🔥BugFix

#283 fix: event_type 명 변경
  llm/views.py
Labels: ❤️‍🔥BugFix

#285 fix: 시나리오 생성 로직 수정 v3
  llm/views.py
Labels: ❤️‍🔥BugFix

#287 fix: 시나리오 생성 로직 변경 v4
  llm/views.py
Labels: ❤️‍🔥BugFix

#289 fix: 시나리오 생성 로직 수정v5
  llm/views.py
Labels: ❤️‍🔥BugFix

#291 fix: 시나리오 생성 로직 수정
  llm/views.py
Labels: ❤️‍🔥BugFix

#279 제발 이번에는 성공해라,,,
  Backend/settings.py
  docker-compose-blue.yml
  grafana.ini
  grafana/data/grafana.db
  nginx.conf
Labels: ❤️‍🔥BugFix

#295 fix: 시나리오 생성 오류 수정v6
  llm/views.py
Labels: ❤️‍🔥BugFix

#297 fix: 시나리오 생성 로직 수정 v7
  llm/views.py
Labels: ❤️‍🔥BugFix

#301 fix: 코드 수정 중에 오류 해결되어서 수정할 필요 없어짐
  docker-compose-blue.yml
  grafana/data/grafana.db
Labels: ❤️‍🔥BugFix

#303 refactor: 증거 이미지 생성 변경
  llm/views.py
Labels: 🔨Refactor

#307 fix: 채팅 생성 오류 수정
  chat/consumers.py
Labels: ❤️‍🔥BugFix

#309 fix: 프롬프팅 보완
  llm/views.py
Labels: ❤️‍🔥BugFix

#310 chore: Create .gitattributes
  .gitattributes
Labels: ⚙️ Chore

#311 fix: Update .gitattributes
  .gitattributes
Labels: ⚙️ Chore, ❤️‍🔥BugFix

#312 fix:: Update .gitattributes
  .gitattributes
Labels: ⚙️ Chore, ❤️‍🔥BugFix

#305 feat: loki, promtail을 이용한 로깅설정 및 장고 모니터링 수정
  grafana/data/grafana.db
  nginx.conf
  prometheus/prometheus.yml
Labels: ✨Feat

#314 fix: Nginx.conf 수정완료
  nginx.conf
Labels: ❤️‍🔥BugFix

#316 fix: 장고 모니터링 코드 수정했어요
  nginx.conf
  prometheus/prometheus.yml
Labels: ❤️‍🔥BugFix

#318 fix:bug fix
  nginx.conf
Labels: ❤️‍🔥BugFix

#319 fix:bug fix fix
  nginx.conf
Labels: ❤️‍🔥BugFix

#321 fix: nginx.conf 코드 수정 완료
  nginx.conf
Labels: ❤️‍🔥BugFix

#323 feat: 플레이 기록 creatd_at 컬럼 추가
  scenario/serializers.py
Labels: ✨Feat

#328 fix: prometheus 메트릭 경로 재지정
  Backend/settings.py
  docker-compose-blue.yml
  prometheus/prometheus.yml
Labels: ❤️‍🔥BugFix

#330 Feat:Blue-Green Deployment 구현
  Backend/settings.py
  Backend/urls.py
  docker-compose-common.yml
  docker-compose-green.yml
  health/urls.py
  health/views.py
  nginx.conf
Labels: ✨Feat

#331 feat and fix:rm myapp
  docker-compose-common.yml
Labels: ✨Feat, ❤️‍🔥BugFix

#333 fix : docker
  docker-compose-common.yml
Labels: ❤️‍🔥BugFix

#334 fix:docker-compose-common bug fix
  docker-compose-common.yml
Labels: ❤️‍🔥BugFix

#336 fix:bug fix
  nginx.conf
Labels: ❤️‍🔥BugFix

#337 fix:bug fix
  nginx.conf
Labels: ❤️‍🔥BugFix

#339 fix: Pipeline EC2 PATH fix
  .github/workflows/ci.yml
Labels: ❤️‍🔥BugFix

#341 fix: 프록시 수정 완료
  Backend/settings.py
  Backend/urls.py
  nginx.conf
Labels: ❤️‍🔥BugFix

#343 feat: 프론트엔드 연동
  Backend/settings.py
Labels: ✨Feat

#347 feat: 시나리오 생성 GET 매서드 추가
  llm/views.py
Labels: ✨Feat

#349 fix: 생성한 GET 매서드 롤백 및 시나리오 불러오기 json 지정
  llm/views.py
  scenario/views.py
Labels: ❤️‍🔥BugFix

#352 fix: task_id 미반환 수정 v2
  suspect/serializers.py
Labels: ❤️‍🔥BugFix

#354 fix: tts 컬럼 추가
  llm/views.py
  suspect/models.py
  suspect/serializers.py
Labels: ❤️‍🔥BugFix

#356 fix: tts 컬럼 null 허용
  suspect/models.py
Labels: ❤️‍🔥BugFix

#358 fix: 추리 성공 시 is_success = true 변경
  suspect/views.py
Labels: ❤️‍🔥BugFix

#360 fix: 장고 모니터링 수정 완료
  Backend/settings.py
  Backend/urls.py
  grafana/data/grafana.db
  nginx.conf
  prometheus/prometheus.yml
  suspect/migrations/0004_suspect_task_id.py
Labels: ❤️‍🔥BugFix

#363 fix: 2차 수정 완료
  nginx.conf
Labels: ❤️‍🔥BugFix
